In [3]:
region_nums = [10, 5, 3]
region_array = []
for x_index in range(region_nums[0]):
    region_array.append([])
    for y_index in range(region_nums[1]):
        region_array[x_index].append([])
        for z_index in range(region_nums[2]):
            region_array[x_index][y_index].append([])
            region_array[x_index][y_index][z_index] = 0
region_array

[[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]]

In [4]:
import copy

original_list = [1, 2, [3, 4]]
shallow_copied_list = copy.copy(original_list)

# Modifying a nested object affects both
shallow_copied_list[2][0] = 99
print(f"Original list after shallow copy modification: {original_list}")
print(f"Shallow copied list: {shallow_copied_list}")

Original list after shallow copy modification: [1, 2, [99, 4]]
Shallow copied list: [1, 2, [99, 4]]


In [6]:
import os

# Specify the directory name
directory_name = "GFG"

# Create the directory
try:
    os.mkdir(directory_name)
    print(f"Directory '{directory_name}' created successfully.")
except FileExistsError:
    print(f"Directory '{directory_name}' already exists.")
except PermissionError:
    print(f"Permission denied: Unable to create '{directory_name}'.")
except Exception as e:
    print(f"An error occurred: {e}")

os.makedirs("GFG/name")

Directory 'GFG' created successfully.


In [19]:
import numpy as np

region_list = np.empty((2, 3, 4))

print(region_list)
try:
    os.mkdir("practice")
except:
    Exception

mcfunction_breaker = open("practice/build.mcfunction", "w")

for i in range(len(region_list)):
    for j in range(len(region_list[i])):
        for k in range(len(region_list[i][j])):
            mcfunction_breaker.write(f"fill ~{32*i} ~{32*j} ~{32*k} ~{32*i + 31} ~{32*j + 31} ~{32*k + 31} air replace minecraft:block_name\n")


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [20]:
region_array = []
for x_index in range(region_nums[0]):
        region_array.append([])
        for y_index in range(region_nums[1]):
            region_array[x_index].append([])
            for z_index in range(region_nums[2]):
                nbt_schematic_temp = "hello"
                region_array[x_index][y_index].append([nbt_schematic_temp])

print (region_array)

[[[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']]], [[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']]], [[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']]], [[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']]], [[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']]], [[['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello'], ['hello'], ['hello']], [['hello